### PR TITLE
Migrate docs site to Docsify

### PR DESCRIPTION
**Pull request by galargh**
This PR enables migration from GitBook to [Docsify](https://docsify.js.org/#/). I used Docsify because it allowed me to use the exact same format/structure as GitBook. This made the migration process really quick.

It introduces [a new landing page](https://github.com/testground/docs/blob/b780a072680b04d7cf1f5920f9cdfe6a4bd85404/.github/workflows/pages.yml) that is required by Docsify.

It sets up [automated deployments](https://github.com/testground/docs/blob/b780a072680b04d7cf1f5920f9cdfe6a4bd85404/.github/workflows/pages.yml) of both `master` and `v0.5.3` branches to GitHub Pages.

It removes Gitbook specific constructs from `.md` files.

Before this PR can be merged, we should:
- [x] update `pages.yml` so that it doesn't point at this branch
- [x] add favicon
- [x] add page metadata
- [x] migrate `v0.5.3` branch to docsify

I'm leaving the above open until we agree with @laurentsenta this is the approach we want to take. 

The current version of the docs site powered by Docsify can be viewed at: https://testground.github.io/docs/

### CODE REVIEW

**Comment by laurentsenta** [comment]
@galargh result looks good, I'll review it today; two questions

- What about we don't spend time on 0.5.3 and use that time to work on releasing 0.6.0? (I guess the previous doc will stay up for some time, and we can link to it)
- Would it make sense to move the docs to the testground/testground repo? So that every change comes with a documentation change?

**Comment by galargh** [comment]
> * What about we don't spend time on 0.5.3 and use that time to work on releasing 0.6.0? (I guess the previous doc will stay up for some time, and we can link to it)

Totally! It was worth spending time thinking about 0.5.3 though because multi-version support in docs is not that obvious. Note to self: look if we can simplify multi-version/language support using https://github.com/palkan/docsify-namespaced (https://evilmartians.com/chronicles/easy-multi-language-multi-version-documentation-with-docsify-git-and-github-actions). At a first glance it looks nicer than what we currently have on this branch.

_EDIT_ I decided not to pursue this now.

> * Would it make sense to move the docs to the testground/testground repo? So that every change comes with a documentation change?

Sounds great too! I'll move this version of repo to `testground/testground/docs` next week. I think it'll be easier to review in this repo though since all the files in `testground/testground` will be new.

**Comment by galargh** [comment]
@laurentsenta I thought of a pretty good reason why we might want to hold off on moving the docs to `testground/testground` - clone size. I don't suppose we want to make every testground user download 30mb worth of docs assets whenever they clone testground. Similarly, we don't want to refrain from adding assets to docs because it affects testground bundle size.

**Comment by galargh** [comment]
@laurentsenta My suggestion would be to:
1. Merge https://github.com/testground/docs/pull/22
1. Merge https://github.com/testground/docs/pull/21
1. Update DNS to point at the new docs
1. Reconsider moving docs to `testground/testground` once we have binary releases there

**Review by laurentsenta — APPROVED** [review]

**Pull request merged**
